# Generated by Django 4.0 on 2021-12-14 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('SkillName', models.CharField(max_length=24, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Job',
            fields=[
                ('JobId', models.AutoField(primary_key=True, serialize=False)),
                ('JobTitle', models.CharField(max_length=100)),
                ('JobSkills', models.ManyToManyField(to='candidateFinderApp.Skill')),
            ],
        ),
        migrations.CreateModel(
            name='Candidate',
            fields=[
                ('CandidateId', models.AutoField(primary_key=True, serialize=False)),
                ('CandidateTitle', models.CharField(max_length=100)),
                ('CandidateSkills', models.ManyToManyField(to='candidateFinderApp.Skill')),
            ],
        ),
    ]
