# Generated by Django 4.0 on 2021-12-14 09:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('candidateFinderApp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='JobSkills',
        ),
        migrations.DeleteModel(
            name='Candidate',
        ),
        migrations.DeleteModel(
            name='Job',
        ),
        migrations.DeleteModel(
            name='Skill',
        ),
    ]
